### ISSUE TITLE
App don't open a second time

### ISSUE THREAD

**Issue by natanielschling** [avaliabrasil/avalia-brasil#10]
User closes app while registering a new place. After that, app don't open anymore: "Infelizmente o Avalia Brasil parou"

**Comment by Klauswk** [comment]
Couldn't reproduce the bug, can you send me your phone version?

**Comment by pedroliman** [comment]
Phone Model:LG Volt - LG-H422

Now I tried to reproduce this problem a few times. I couldn't define steps to reproduce it. After trying to submit answers a few times the app eventualy stops working.

**Comment by pedroliman** [comment]
This bug is not showing up anymore.
