### ISSUE TITLE
Post new place to /survey is crashing

### ISSUE THREAD

**Issue by pedroliman** [avaliabrasil/avalia-brasil#51]
POST: http://api.avaliabrasil.org/survey/fafdafdsafdafdas

{"userId":"1","newPlace":true,"placeTypeId":"104","address":"Rua Osvaldo Aranha - Centro, São Leopoldo","name":"Instituto Rio Branco","cityName":"São Leopoldo","stateLetter":"RS","answers":[{"questionId":"1","questionType":"likert","answer":"5"},{"questionId":"2","questionType":"likert","answer":"2"},{"questionId":"3","questionType":"likert","answer":"3"},{"questionId":"4","questionType":"likert","answer":"4"},{"questionId":"5","questionType":"likert","answer":"2"},{"questionId":"6","questionType":"likert","answer":"4"},{"questionId":"7","questionType":"likert","answer":"2"},{"questionId":"8","questionType":"likert","answer":"2"},{"questionId":"9","questionType":"likert","answer":"4"},{"questionId":"10","questionType":"likert","answer":"2"},{"questionId":"11","questionType":"likert","answer":"4"},{"questionId":"12","questionType":"likert","answer":"2"},{"questionId":"13","questionType":"likert","answer":"4"},{"questionId":"14","questionType":"likert","answer":"5"},{"questionId":"15","questionType":"likert","answer":"2"},{"questionId":"16","questionType":"likert","answer":"3"},{"questionId":"17","questionType":"likert","answer":"1"},{"questionId":"18","questionType":"likert","answer":"4"},{"questionId":"19","questionType":"likert","answer":"2"},{"questionId":"20","questionType":"likert","answer":"3"},{"questionId":"21","questionType":"likert","answer":"1"},{"questionId":"22","questionType":"likert","answer":"3"},{"questionId":"23","questionType":"comment","answer":"Mai's ounmenos"}]}

Returns:
INSERT INTO place (id_type, name, address, created_at, updated_at, status, id_city, google_id)
        VALUES('104', 'Instituto Rio Branco', 'Rua Osvaldo Aranha - Centro, São Leopoldo', '2016-10-13 22:25:32', '2016-10-13 22:25:32', 1, 5000, 'ChIJfzxguU5oGZURJHvfRv5REzA')

**Comment by natanielschling** [comment]
Done.
