### ISSUE TITLE
Trending graph doesn't show month's names in X axis

### ISSUE THREAD

**Issue by natanielschling** [avaliabrasil/avalia-brasil#8]

**Comment by Klauswk** [comment]
The API send me back the data structure as below:

 [{"id":"211","name":"UBS Roselandia","address":"Rua Castro Alves, 166 - Rio Branco, Novo Hamburgo","city":"Novo Hamburgo","state":"RS","category":"Outro","type":"Outro","qualityIndex":[{"month":"2016.5","value":"70.07575758"}],"rankingPosition":{"national":"1","regional":"1","state":"1","municipal":"1"},"rankingStatus":{"national":"none","regional":"none","state":"none","municipal":"none"},"lastWeekSurveys":"0","comments":[{"description":"teste"},{"description":"N\u00e3o gostei do atendimento"},{"description":"dddd"}]}]

Can we change the month to an timestamp like? Then we can fetch back the full date info

**Comment by pedroliman** [comment]
Duplicated with #18, let's talk there.
